# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/tx/Basys-3-Master.xdc

# IP: ip/clk_wiz_2/clk_wiz_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_2 || ORIG_REF_NAME==clk_wiz_2} -quiet] -quiet

# XDC: c:/working/FPGA_HARMAN/250606_TOP_VGA_Project_v2_0851/250606_TOP_VGA_Project_v2_0851.gen/sources_1/ip/clk_wiz_2/clk_wiz_2_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_2 || ORIG_REF_NAME==clk_wiz_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/working/FPGA_HARMAN/250606_TOP_VGA_Project_v2_0851/250606_TOP_VGA_Project_v2_0851.gen/sources_1/ip/clk_wiz_2/clk_wiz_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_2 || ORIG_REF_NAME==clk_wiz_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/working/FPGA_HARMAN/250606_TOP_VGA_Project_v2_0851/250606_TOP_VGA_Project_v2_0851.gen/sources_1/ip/clk_wiz_2/clk_wiz_2_ooc.xdc
