# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/tx/Basys-3-Master.xdc

# IP: ip/clk_wiz_1/clk_wiz_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] -quiet

# XDC: c:/working/FPGA_HARMAN/250613_VGA_final/250613_VGA_final.gen/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/working/FPGA_HARMAN/250613_VGA_final/250613_VGA_final.gen/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/working/FPGA_HARMAN/250613_VGA_final/250613_VGA_final.gen/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc
